### ISSUE TITLE
TODO: Make ping pong paddle and/or bat gripper

### ISSUE THREAD

**Issue by tyler-ingebrand** [jbonyun/cs391r#1]
Currently all robotic arms and grippers have some form of claw for obvious reasons. So we need to create a custom ping pong shaped paddle to hit things with. This should be possible by modifying or generating new Mujoco (or equivalent) files. Either we need to 1) create an entire arm, likely by modifying an existing arm, or 2) create a gripper if that is supported. The second option is preferred as it is less work and more reusable. 

It is likely possible as you can do the following in code to create a robot arm:
````
from robosuite.models.robots import Panda,IIWA

mujoco_robot = IIWA()  # Iiwa will stay balanced in straight up direction
#mujoco_robot = Panda()  # Panda will humorously flop over if you don't give it control

from robosuite.models.grippers import gripper_factory

gripper = gripper_factory('PandaGripper')
mujoco_robot.add_gripper(gripper)
````
Which option is better should be investigated and implemented. This issue is done when you can create a robotic arm with a paddle shaped gripper, and load it into a simulation.

**Comment by jbonyun** [comment]
Works. I am using it attached to the arm in the merge I just did to master. I did change *how* we use it to avoid dropping the code into the robosuite source tree. For now I think that's better.
