### ISSUE TITLE
TODO: Make ping pong environment

### ISSUE THREAD

**Issue by tyler-ingebrand** [jbonyun/cs391r#2]
Assuming we can create a ping pong paddle arm, we need to create the rest of the environment. This means we need to load the following into a robosuite simulation: 
1) Some sort of long table to bounce balls against
2) Some reasonably sized ball with reasonable physics values (Velocity damping, other values?)
3) Some sort of trajectory generation, so we can "throw" balls at the robotic arm
4) Randomize trajectory generation so every trajectory is unique. This is necessary to not overfit to a single trajectory. 

Dont worry about the actual arm, that is being handled by another ticket. The arm will be placed at the end of the table. Use a stand-in arm for now.

**Comment by jbonyun** [comment]
Plan is to have empty space with no gravity. Just the arm.
Then to generate random ball starting point/vels such that it will intersect the reachable "sphere" (it's actually a weird shape; not sure how I'll deal with that) of the robot arm.
The ball stuff is the hard part -- adding back gravity, walls, table, etc will be easy, when we are ready for it.

**Comment by jbonyun** [comment]
Progress made on `jeff` branch for now. Makes an arm, in space, without gravity, with a ball, with initial velocity on the ball, resulting in a collision in which the ball bounces off the arm.

Still need to work on the random trajectory thing.

**Comment by jbonyun** [comment]
Random trajectories are finished. The basics of control are demonstrated. The bat is attached.

At this point, I think this issue is resolved.
