### ISSUE TITLE
TODO: Combine paddle gripper and ping pong environment into a gym environment

### ISSUE THREAD

**Issue by tyler-ingebrand** [jbonyun/cs391r#3]
Given the previous 2 tickets are implemented, we should be able to combine them to create a ping pong environment that fits the gym interface. The gym interface allows us to interface with RL algorithms. This may or may not be a trivial ticket depending on how robosuite does things.

**Comment by jbonyun** [comment]
The environment (with paddle/bat) is done. But now this has to become a gym. Some details are still remaining, that I assume the gym will need. Like we will have to have some way of determining the reward -- which means detecting collisions (of the ball+bat, but ideally also robot to itself and things other than the ball).

**Comment by jbonyun** [comment]
Working on wrapping in robosuite environment. #8

**Comment by jbonyun** [comment]
I think we can call this done, since we're running it in sb3.
