### ISSUE TITLE
TODO: Integrate gym interface withstable baselines. Figure out recurrence?

### ISSUE THREAD

**Issue by tyler-ingebrand** [jbonyun/cs391r#4]
Given we will have a gym environment outputting image files, we need to use both CNN and recurrence. Stable baselines provides RL algorithms to use out of the box. PPO2 should be able to handle both CNN and recurrence. Thus we have the following steps:
1) Integrate stable baselines with any gym environment
2) Add recurrence
3) Add CNN
4) Once ping pong env is set up, run a stable baseline alg on ping pong.

**Comment by jbonyun** [comment]
Yeah, all this was done.
